[package]
name = "lambda-script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpds = "0.12.0"
educe = "0.4.20"
